# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gateway.proto import core_engine_pb2 as core__engine__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreEngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostIngestion = channel.unary_unary(
                '/semlog.core_engine.CoreEngineService/PostIngestion',
                request_serializer=core__engine__pb2.IngestLogRequest.SerializeToString,
                response_deserializer=core__engine__pb2.IngestLogResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/semlog.core_engine.CoreEngineService/GetStatus',
                request_serializer=core__engine__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=core__engine__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class CoreEngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostIngestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostIngestion': grpc.unary_unary_rpc_method_handler(
                    servicer.PostIngestion,
                    request_deserializer=core__engine__pb2.IngestLogRequest.FromString,
                    response_serializer=core__engine__pb2.IngestLogResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=core__engine__pb2.GetStatsRequest.FromString,
                    response_serializer=core__engine__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semlog.core_engine.CoreEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('semlog.core_engine.CoreEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreEngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostIngestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semlog.core_engine.CoreEngineService/PostIngestion',
            core__engine__pb2.IngestLogRequest.SerializeToString,
            core__engine__pb2.IngestLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semlog.core_engine.CoreEngineService/GetStatus',
            core__engine__pb2.GetStatsRequest.SerializeToString,
            core__engine__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
