# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ore_engine.proto\x12\x12semlog.core_engine\"3\n\x10IngestLogRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"O\n\x11IngestLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\"\x11\n\x0fGetStatsRequest\"Z\n\x10GetStatsResponse\x12\x12\n\ntotal_logs\x18\x01 \x01(\t\x12\x17\n\x0f\x63ompressed_logs\x18\x02 \x01(\t\x12\x19\n\x11\x63ompression_ratio\x18\x03 \x01(\t2\xc9\x01\n\x11\x43oreEngineService\x12\\\n\rPostIngestion\x12$.semlog.core_engine.IngestLogRequest\x1a%.semlog.core_engine.IngestLogResponse\x12V\n\tGetStatus\x12#.semlog.core_engine.GetStatsRequest\x1a$.semlog.core_engine.GetStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTLOGREQUEST']._serialized_start=41
  _globals['_INGESTLOGREQUEST']._serialized_end=92
  _globals['_INGESTLOGRESPONSE']._serialized_start=94
  _globals['_INGESTLOGRESPONSE']._serialized_end=173
  _globals['_GETSTATSREQUEST']._serialized_start=175
  _globals['_GETSTATSREQUEST']._serialized_end=192
  _globals['_GETSTATSRESPONSE']._serialized_start=194
  _globals['_GETSTATSRESPONSE']._serialized_end=284
  _globals['_COREENGINESERVICE']._serialized_start=287
  _globals['_COREENGINESERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
